### ISSUE TITLE
Notebooks to Implement

### ISSUE THREAD

**Issue by barpit20** [jump-dev/JuMPTutorials.jl#1]
1. Introduction
  - [x] An Introduction to Julia
  - [x] Getting started with JuMP
  - [x] Variables, Constraints and Objective
  - [x] Solutions
  - [x] Solvers
2. Using JuMP
  - [x] Reading from Data files
  - [x] Problem Modification
  - [x] Nonlinear Modeling
3. Optimization Concepts
  - [x] Integer Programming
  - [x] Conic Programming
  - [x] Benders Decomposition
4. Modeling Examples (Currently a list of topics to pick examples from)
  - [x] Sudoku
  - [x] Power Systems
  - [x] Network Flows
  - [x] Statistics
  - [ ] Approximation and Fitting
  - [x] Geometric Problems
  - [ ] Control theory
  - [x] Graph Theory
  - [ ] Economics/Econometrics
  - [x] Finance
  - [x] Rocket Control
  - [ ] Travelling Salesman Problem

Note that this is a tentative list and some notebooks can be combined or split into two parts. Topics such as non-linear modelling, callbacks and column generation are ongoing dev efforts. Things are subject to change there and notebooks for them will only be created after they are finalized.

**Comment by barpit20** [comment]
The following notebooks have been pushed back for now 
 - [ ] Optimizing Code
  - [ ] Building Large Scale Models
  - [ ] Using Different Julia Data Types
  - [ ] Duality

**Comment by Wikunia** [comment]
Regarding TSP I wrote: https://opensourc.es/blog/mip-tsp a while back. 
It's without callbacks just a loop of solving + disallowing cycles. If this is of interest I can add a clean version of this here.

**Comment by matbesancon** [comment]
@Wikunia yes we might take it as a basis, I think it would be a good use case to introduce callbacks, pinging @mtanneau

**Comment by barpit20** [comment]
@Wikunia It would be great if you could add your tutorial here. I think it would be good to have both versions, with and without callbacks.

**Comment by jimorlin** [comment]
It would be really helpful to add a tutorial on plotting or graphing within Julia.  It could be at the level of your tutorial on "reading data."

**Comment by AlessandroGaeta1** [comment]
Hi!
I wrote a Spacecraft Trajectory Optimizer with Avoidance Constraints program (in JuMP) using Mixed-Integer Linear programming, with at the end a simple plot of the solution.
Is there someone to contact to see if a tutorial about this topic might be useful?

**Comment by blegat** [comment]
Here is the right place, the contribution is welcome!

**Comment by odow** [comment]
Closing because I'm going to archive this repository.
