### ISSUE TITLE
Run Notebooks in the Browser

### ISSUE THREAD

**Issue by barpit20** [jump-dev/JuMPTutorials.jl#22]
We need to explore services such as Binder and Google Colab to enable people to try out the tutorials in the browser itself without having to download anything.

**Comment by joaquimg** [comment]
What about juliaBox?
Maybe a step by step of how to load them in juliaBox is good enough.

**Comment by barpit20** [comment]
JuliaBox currently uses JuMP 0.18.5 thus the notebooks do not work with it. Binder seems to be our best option.
