### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by odow** [jump-dev/JuMPTutorials.jl#28]
Very cool! This is going to be a great resource. 

Just a query re the tests. It seems like the tests run all of the code in the notebooks, but I couldn't find any checks using `@test` that the output is what we expect. Is there a way to add some tests? Or is it sufficient to just run the code and check that it doesn't error?

**Comment by barpit20** [comment]
We do use `@test` to check that the output is correct in the `runtests.jl` file. For example, in case of the sudoku notebook:
https://github.com/barpit20/JuMPTutorials.jl/blob/1f3c26e316977021519c50007748af291543b465/test/runtests.jl#L33-L43

**Comment by odow** [comment]
Ah. I was looking in the wrong place. Follow up: can we test that the printed output is the same? I can imagine the notebooks getting out of date if printing changes or there are deprecation warnings or something.

**Comment by barpit20** [comment]
I'll think and get back to you on this. We'll probably need to store outputs in a file and compare.

**Comment by chriscoey** [comment]
@odow do you know of any other packages that do something like that?

**Comment by odow** [comment]
I have no ideas. Just wondering.

**Comment by matbesancon** [comment]
@odow we could generalize using `@test` in the scripts themselves to validate things (objective value, etc)

**Comment by odow** [comment]
Closing because these are now in the JuMP repo. They doctests get run on every commit, and some tutorials have `@test` to check outputs.
