### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by barpit20** [jump-dev/JuMPTutorials.jl#32]
The notebooks in the old juliaopt-notebooks repo had the [Creative Commons Attribution-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/). Do we need to look into licensing for these tutorials as well?

@mlubin @juan-pablo-vielma

**Comment by mlubin** [comment]
Yes. It's important to have a valid license on the tutorials. The MIT license is valid for documentation but is designed for code more than for text. That said, MIT seems reasonable.
