### ISSUE TITLE
Consistency check

### ISSUE THREAD

**Issue by mlubin** [jump-dev/JuMPTutorials.jl#35]
It would be nice if there was a CI check that the notebooks correspond to the script files that are checked in. It could be easy to forget to regenerate a notebook when modifying a script.

**Comment by barpit20** [comment]
We can add a check that the last modified time for the Julia file should be earlier than the corresponding Jupyter notebook. It will not check the contents but will ensure that the notebook file was regenerated.

**Comment by chriscoey** [comment]
@mlubin do you have any specific ideas on how to do this, or links to other repos that do something similar?

**Comment by mlubin** [comment]
I can think of three different approaches:

1. Regenerate the notebooks on travis and check that they match the
checked-in version exactly.
2. Regenerate the notebooks on travis and check that the input and text
matches what's checked in, allowing for the cell outputs to differ. (Paths
and timings would normally different if the notebooks are generated on
different systems.)
3. Don't check in the notebooks. Instead, generate then as build artifacts,
like https://docs.travis-ci.com/user/deployment/releases/. I don't have
experience with this option, not sure if it is actually a solution for our
use case.

**Comment by odow** [comment]
Closing because I'm going to archive this repository.
