### ISSUE TITLE
move to JuliaOpt Github organization

### ISSUE THREAD

**Issue by chriscoey** [jump-dev/JuMPTutorials.jl#38]
I don't have the ability to do this since I don't own the repo. @barpit20 you can try going to settings and transferring ownership to JuliaOpt.

**Comment by barpit20** [comment]
I am not able to transfer ownership either because it says I don't have the permission to create repositories in the JuliaOpt organization. Should I first transfer the repo to you and then you can make the move? How did it work for the Dualization project?

**Comment by blegat** [comment]
Transfer it to me and I'll transfer it to JuliaOpt, that's what we did for the two other GSoC repos

**Comment by barpit20** [comment]
Done.

**Comment by blegat** [comment]
Transfer done :)
