### ISSUE TITLE
replace eye with I (UniformScaling) in experiment design notebook

### ISSUE THREAD

**Issue by chriscoey** [jump-dev/JuMPTutorials.jl#39]
https://github.com/JuliaOpt/JuMPTutorials.jl/blob/5f11c956c6184fcc5eb3825ede3998df6c3e48bd/script/modelling/experiment_design.jl#L59

"eye" is a Matlab-ism that is discouraged in Julia. @barpit20 Can you try putting `I` directly into the `@constraint`? It it doesn't work, please file another feature request on JuMP (or add to the Diagonal feature request).

**Comment by matbesancon** [comment]
@chriscoey I'm looking at it now, one possibility is to use `Diagonal` and keep the constraint expression more or less as-is, the second is to reformulate the constraint with direct slices instead of multiplying by a slice of I

**Comment by odow** [comment]
Closing because I'm going to archive this repository.
