### ISSUE TITLE
Test on OSX and Windows

### ISSUE THREAD

**Issue by joaquimg** [jump-dev/JuMPTutorials.jl#59]
I think we should keep tutorials accessible from all the three systems.

**Comment by matbesancon** [comment]
Yup, travis support all of them now I think. The only downside is that builds usually take forever on windows and osx

**Comment by joaquimg** [comment]
Maybe we restrict windows and OSX to a single julia version?

**Comment by matbesancon** [comment]
Yes agreed, the 1.0? since this is the LTS that we are more likely to break

**Comment by blegat** [comment]
1.0 sounds good

**Comment by odow** [comment]
Closing because I'm going to archive this repository.
