### ISSUE TITLE
follow conventions in latest JuMP style guide

### ISSUE THREAD

**Issue by chriscoey** [jump-dev/JuMPTutorials.jl#6]
see http://www.juliaopt.org/JuMP.jl/dev/style/
there are some subtle points like whitespace around binary operators, function and variable naming, etc that may require some minor changes to the code already committed

**Comment by chriscoey** [comment]
if any of the points in the style guide are unreasonable to conform to in the tutorials (eg function/variable naming perhaps) then let's discuss here

**Comment by chriscoey** [comment]
also there could easily be contradictions in the style guide - it is a work in progress. don't hesitate to propose changes in the gitter channel or on the JuMP repo

**Comment by barpit20** [comment]
Sorry about that. I will go through the style guide again and recheck.

**Comment by barpit20** [comment]
Is using a number in the name of the variable such as `Graph1` appropriate? The JuMP and Julia style guides don't refer to numbers in the variable names.

**Comment by chriscoey** [comment]
I'm not sure why it would be necessary - is there a more informative name you can give it? Is it a jump model variable or a Julia variable? Julia variables shouldn't start with capitals.

**Comment by barpit20** [comment]
It is a Julia variable representing the adjacency matrix of a graph. I am using multiple graphs in one notebook so I wanted to use simple names. Is something like `vertex_cover_graph` too complex?

As I am using each graph only once, another way could be to just use the name `g` or `graph` and overwrite it every time.

**Comment by chriscoey** [comment]
`vertex_cover_graph` is definitely not too long. 

if you are only managing one graph at a time, then `graph` is ok.

**Comment by barpit20** [comment]
I think I have got the hang of it. I'll get this issue resolved soon.
