### ISSUE TITLE
MLE example in nonlinear_modelling.ipynb broken?

### ISSUE THREAD

**Issue by cdeil** [jump-dev/JuMPTutorials.jl#62]
Currently in nonlinear_modelling.ipynb for the MLE example I see this result:
```
μ = 0.0
mean(data) = -0.02534297022835935
σ^2 = 1.0
var(data) = 1.0112373171501061
MLE objective: -0.0
```

Is mu=0 and objective=0 a bug? Shouldn't mu match mean?

I have IJulia install issues, can't get the notebook to run unfortunately to investigate.

**Comment by matbesancon** [comment]
after digging, there seems to be a numerical issue in the likelihood function, the log should be used directly here
