### ISSUE TITLE
Explain how to install dependencies with conda

### ISSUE THREAD

**Issue by cdeil** [jump-dev/JuMPTutorials.jl#64]
Could you please add a little information to help new Julia users to get set up for the JuMPTutorials.jl in the README?

I installed Julia via Homebrew and installed JuMP and a few solvers via the Julia Pkg manager, and it worked. Then I installed IJulia and for a short time it worked, I could start a Julia notebook from the launcher after `jupyter lab`.

Then I tried to get the JuMPTutorials.jl to run, and ran this command from your `.travis.yml`:
```
julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
```
Now I'm in deep trouble, I get errors like this when I try to start `jupyter lab`:
```
ERROR: LoadError: Failed to precompile IJulia
```
See https://gist.github.com/cdeil/020d25045b6b4ca4dd67b53426b782b3

I'm experienced with Python and conda, but I'm completely new to Julia, don't know about Julia environments or `Project.toml` and `Manifest.toml` or how those interact with my conda environments. Would appreciate a tip how to remove the broken env / install. But my main feature request here is some docs in the README what the "good" or "normal" way to get set up for the Jump tutorials locally is.

**Comment by odow** [comment]
Short answer is that IJulia and Julia do not work well with conda; IJulia ships with its own version of miniconda.

Install Julia from julialang.org.

Then follow the instructions at https://github.com/JuliaLang/IJulia.jl to install IJulia.

**Comment by cdeil** [comment]
And for the tutorials, I presume there's some command to use `Project.toml` and/or `Manifest.toml` to install all dependencies with working versions? Is this the correct command that I should run?
```
julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
```

**Comment by matbesancon** [comment]
to run a script with the current environment, you need julia --project
and then run the script or test file
Relevant tutorial here: https://julialang.github.io/Pkg.jl/v1/

**Comment by odow** [comment]
Closing because I'm going to archive this repository.
