### ISSUE TITLE
Roadmap for JuMPTutorials

### ISSUE THREAD

**Issue by frapac** [jump-dev/JuMPTutorials.jl#68]
Hi, 
I am opening this issue to sum up a few discussions we had during the JuMP dev calls. I would like to know what are the current plans concerning : 

- the automatic generation of the files in `notebooks/` in travis 
- the status of JuMPTutorials w.r.t. JuMP: do we still plan on merging `JuMPTutorials` in the JuMP repo?
- also, is there any plan to generate a HTML version of the tutorials, to include them directly in the [JuMP's website](jump.dev) (e.g. in a [cvxpy fashion](cvxpy.org))? 

Again, this issue is just to port the discussion in an asynchronous place, and I would be happy to help on improving JuMPTutorials.

**Comment by matbesancon** [comment]
> the automatic generation of the files in notebooks/ in travis

agreed

> the status of JuMPTutorials w.r.t. JuMP: do we still plan on merging JuMPTutorials in the JuMP repo?

> the status of JuMPTutorials w.r.t. JuMP: do we still plan on merging JuMPTutorials in the JuMP repo?

I think yes, even though it can make the JuMP repo a bit heavy (plus handling multi-project repos with Pkg is still ongoing work I believe)

> also, is there any plan to generate a HTML version of the tutorials, to include them directly in the JuMP's website (e.g. in a cvxpy fashion)?

I believe this should be manageable by adding a new function in the src itself to build html pages

**Comment by matbesancon** [comment]
To complete this issue following Thursday's JuMP meeting:
- Switch the generation process from Weave to Literate
- Figuring out the notebook building on CI
- If possible, running tests from the scripts directly while avoiding the heavier parts like plotting

**Comment by matbesancon** [comment]
Ultimately this repo should be merged with JuMP.jl itself with a /tutorials folder

**Comment by odow** [comment]
To update: I've started this process here: https://github.com/jump-dev/JuMP.jl/tree/master/docs/src/tutorials

**Comment by odow** [comment]
This process is mostly complete. Closing in favor of https://github.com/jump-dev/JuMP.jl/issues/2483
