### ISSUE TITLE
N-Queens Tutorial

### ISSUE THREAD

**Issue by mthelm85** [jump-dev/JuMPTutorials.jl#69]
Hello,

I have created a tutorial for the N-Queens problem that I'd be more than happy to contribute here if you all are interested. It can be viewed here:

https://github.com/mthelm85/nqueens/blob/master/N-Queens.ipynb

I'm happy to flesh it out, make changes, etc. If you all would like to include this, let me know and I'll figure out how to submit a pull request ; )

**Comment by blegat** [comment]
It would be a nice addition in my opinion !

**Comment by matbesancon** [comment]
You can look at the different examples for preparing your PR, the code is in `script/`, the comments and section titles are formatted as special comments starting with: `#'`
