### ISSUE TITLE
Broken CI on master + Julia1.5

### ISSUE THREAD

**Issue by mtanneau** [jump-dev/JuMPTutorials.jl#73]
Just for tracking.

The failure is only on Julia 1.5 at this point, and seems to come from the `Weave` module.
The error message is
```julia
ERROR: LoadError: InitError: Evaluation into the closed module `Markdown` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `Markdown` with `eval` during precompilation - don't do this.
```

**Comment by matbesancon** [comment]
thanks, the corresponding issue in Weave is:
https://github.com/JunoLab/Weave.jl/issues/356

**Comment by odow** [comment]
Closing because this seems to be resolved. CI tests on `'1'`.
