### ISSUE TITLE
Clean up test folder

### ISSUE THREAD

**Issue by joaquimg** [jump-dev/JuMPTutorials.jl#75]
Most of the files there are the same as the scripts. The only difference is that comments are removed.
Comments are not executed anyway... we should just run the script folder.

**Comment by matbesancon** [comment]
I think you also have the tangle=false block which avoids running some parts, like plots or things yielding errors on purpose

**Comment by odow** [comment]
Closing as won't-fix. We're moving the tutorials to JuMP, and the tests do indeed run the scripts directly.
